### PR TITLE
[bsp][ESP32] add spi custom configuration function and enhance muti object initliz…

### PR DESCRIPTION
**Pull request by 1078249029**
…ation and setting

## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)
#5941 

#### 你的解决方案是什么 (what is your solution)
improve spi driver

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: bsp/ESP32_C3

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)
- [ ] 如果是新增bsp, 已经添加ci检查到[.github/workflows/bsp_buildings.yml](workflows/bsp_buildings.yml)  详细请参考链接[BSP自查](https://www.rt-thread.org/document/site/#/rt-thread-version/rt-thread-standard/development-guide/bsp-selfcheck/bsp_selfcheck)

### CODE REVIEW

**Comment by supperthomas** [comment]
可否参考：
https://github.com/RT-Thread/rt-thread/blob/master/bsp/nrf5x/nrf52832/.ci/attachconfig/ci.attachconfig.yml
添加yml文件，提供CI测试。

**Comment by 1078249029** [comment]
esp32原来的bsp只能ble，wifi功能二选一，我这里分两个ci文件做测试，我看stm就是这个逻辑，但他们不是yaml文件并且写法有些不同。我不清楚ci写的对不对。下面是stm的ci代码：
```c
# scons: --strict

CONFIG_PKG_USING_AT_DEVICE=y

# Quectel M26/MC20
CONFIG_AT_DEVICE_USING_M26=y
CONFIG_AT_DEVICE_M26_INIT_ASYN=y

# Quectel EC20
CONFIG_AT_DEVICE_USING_EC20=y
CONFIG_AT_DEVICE_EC20_INIT_ASYN=y

# Espressif ESP32
CONFIG_AT_DEVICE_USING_ESP32=y
CONFIG_AT_DEVICE_ESP32_INIT_ASYN=y
```

**Comment by supperthomas** [comment]
改下后缀为yml

**Comment by supperthomas** [comment]
=n不用特别添加

**Comment by 1078249029** [comment]
formatting工具貌似不能格式化endline空行？

**Comment by supperthomas** [comment]
请使用验证过的config放到yml文件中，这个PR
```
devices.spi:
    kconfig:
      - CONFIG_RT_USING_SPI=y
      - CONFIG_BSP_USING_SPI=y
      - CONFIG_BSP_USING_SPI2=y
```
确保yml中的配置是期望的配置。

**Comment by BernardXiong** [comment]
> [CLA assistant check](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9643) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RT-Thread/rt-thread?pullRequest=9643) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RT-Thread/rt-thread?pullRequest=9643) it.

还请签署下CLA，谢谢

**Comment by supperthomas** [comment]
请统一放到一个文件中     .ci/attachconfig/ci.attachconfig.yml

**Comment by 1078249029** [comment]
> 请统一放到一个文件中 .ci/attachconfig/ci.attachconfig.yml



> 请统一放到一个文件中 .ci/attachconfig/ci.attachconfig.yml

目前bsp的ble驱动与wifi驱动有冲突，我想分别进行组件测试，如果放到一一个文件里的话需要修改[bsp的workflow](https://github.com/RT-Thread/rt-thread/blob/master/.github/workflows/bsp_buildings.yml)，考虑后期维护方便还是分开放比较好？

**Comment by 1078249029** [comment]
根据 https://github.com/RT-Thread/rt-thread/issues/5941#issuecomment-1787513664 发现开启ble编译有问题，需要添加空的app_main函数

**Review by supperthomas — APPROVED** [review]

**Comment by supperthomas** [comment]
感谢贡献

**Pull request merged**
