### PR TITLE
BSP: STM32: STM32H750-ART-PI: Make Rtt as a generic bootloader on art-pi board

### PR DESCRIPTION
**Pull request by dillon-min**
To make Rtt working on stm32h750's 128k internal flash as generic bootloader,
download other fw by ymode(console) ,install to qspi/spi flash.

This patch add following changes:
1, set qspi flash as two part, u-boot/kernel
2, set spi flash as rootfs, use jffs2 filesystem
3, support download u-boot/kernel by ymodem(console)
4, switch back to MSP before jump to other fw's code

Signed-off-by: dillon.minfei <dillon.minfei@gmail.com>

## 拉取/合并请求描述：(PR description)

[
Why:  to make life easer, set a bootloader (based on rt-thread) running at art-pi's internal flash. download app to qspi flash, download data to spi flash, jump to qspi flash.

Tested: was verified on art-pi board, with detail process guide and log in README-linux.md
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [Y] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [Y] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [Y] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [Y] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [Y] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [Y] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [Y] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

### CODE REVIEW

**Comment by dillon-min** [comment]
Hi All,

Should i add packages/fal-v0.5.0 to commit ? it's seems conflict with .gitignore, and not strictly necessary.
Is there a bug with patch check system?

Thanks

**Comment by BernardXiong** [comment]
So, this bsp is a bootloader in default? What do other guys think and use?

**Comment by dillon-min** [comment]
> So, this bsp is a bootloader in default? What do other guys think and use?

Hi BernardXiong,

Thanks for response. I'm not intend to make this bsp as a bootloader. but base on art-pi's hardware resources.
- 8MiB QSPI Flash (Xip)
- 16MiB SPI Flash (Be managed by DFS or other filesystem)
- 32MiB SDRAM
- 128KiB flash
- 1MiB sram

128KiB internal flash + 8MiB QSPI flash, i suppose to nobody will just only use internal flash as running fw, and save data to qspi flash. so, setup a bootloader working in internal flash, download second fw(app) to qspi flash, filesystem to spi flash, boot app, just like 'art-pie/sdk-bsp-stm32h750-realthread-artpi/projects/art_pi_qboot/' did. 

This patch has a bit different with art_pi_qboot:
1, a tiny art_pi_qboot (not encrypt/decrypt, no fw verification)
2, don't use a part of spi flash to store download fw (directly write to qspi flash)
   for robust product purpose, user should add fw verification before jump to app.
   there is 30KiB space left (under release build) for this case.
3, add switch msp back (for second fw, both of rt-thread and linux are expect msp)

since art_pi_bootloader and art_pi_qboot has already in art-pie's git repository, i'm not sure it's necessary to add a third bootloader to it?

thanks.

**Review by supperthomas — APPROVED** [review]
Thanks for your code

**Comment by BernardXiong** [comment]
> > So, this bsp is a bootloader in default? What do other guys think and use?
> 
> Hi BernardXiong,
> 
> Thanks for response. I'm not intend to make this bsp as a bootloader. but base on art-pi's hardware resources.
> 
> * 8MiB QSPI Flash (Xip)
> * 16MiB SPI Flash (Be managed by DFS or other filesystem)
> * 32MiB SDRAM
> * 128KiB flash
> * 1MiB sram
> 
> 128KiB internal flash + 8MiB QSPI flash, i suppose to nobody will just only use internal flash as running fw, and save data to qspi flash. so, setup a bootloader working in internal flash, download second fw(app) to qspi flash, filesystem to spi flash, boot app, just like 'art-pie/sdk-bsp-stm32h750-realthread-artpi/projects/art_pi_qboot/' did. 
> 
> This patch has a bit different with art_pi_qboot:
> 1, a tiny art_pi_qboot (not encrypt/decrypt, no fw verification)
> 2, don't use a part of spi flash to store download fw (directly write to qspi flash)
>    for robust product purpose, user should add fw verification before jump to app.
>    there is 30KiB space left (under release build) for this case.
> 3, add switch msp back (for second fw, both of rt-thread and linux are expect msp)
> 
> since art_pi_bootloader and art_pi_qboot has already in art-pie's git repository, i'm not sure it's necessary to add a third bootloader to it?
> 
> thanks.

This is just a general BSP, not a bootloader. It should provide a simple template for developers to add their own applications.

What do you think?

**Pull request closed without merging**
