### PR TITLE
add atomics for cortex-m7 port, including keil, gcc and iar

### PR DESCRIPTION
**Pull request by EDI-Systems**
### Summary of this Pull Request (PR)

- Add atomics for Cortex-M7 port, which makes interrupt entering & exiting quicker.
- If this patch is accepted, the same would be added for Cortex M3/4 as well.

### Intent for your PR

- [ ] This PR is for a code-review and is intended to get feedback.
- [x] This PR is mature, and ready to be integrated into the repo.

### Reviewers (Mandatory):

@BernardXiong @TanekLiang 

### Code Quality

As part of this pull request, I've considered the following:

- [x] Coding style
- [x] All redundant code removed
- [x] No impact on project structure
- [x] No garbage code

### Testing

- Keil v5 compilation and atomic testing passed.
- IAR and GCC branches are not tested (I don't have the environment) but they should work.

### CODE REVIEW

**Comment by BernardXiong** [comment]
It's better to implement atmoic operations, like rt_atmoic_add, rt_atmoic_sub etc.

**Comment by EDI-Systems** [comment]
Now I've added all atomics for rvds.

**Comment by BernardXiong** [comment]
Please do not submit a new bsp. Please do not submit other files, such as debug, log, setting files etc.

**Comment by EDI-Systems** [comment]
I guess I messed it up.

**Pull request closed without merging**
