### PR TITLE
[components][dfs] remove jffs2 and uffs

### PR DESCRIPTION
**Pull request by yangjie11**
## 拉取/合并请求描述：(PR description)

[
由于uffs、jffs2组件的license问题，将其从源码移除。
会将uffs、jffs2作为软件包
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

### CODE REVIEW

**Comment by wosayttn** [comment]
Where is the uffs/jffs2 软件包?

**Comment by mysterywolf** [comment]
将会，等删除之后再做，现在你还搜索不到



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 12, 2021 09:42 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] [components][dfs] remove jffs2 and uffs (#4449)




 
Where is the uffs/jffs2 软件包?

**Comment by wosayttn** [comment]
Noted, Thanks.
Our NK-980IOT board need the UFFS package on SPI NAND flash.
https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/nk-980iot

**Comment by mysterywolf** [comment]
不用担心 过几天补上之后 可以在kconfig里边设置对软件包的依赖 在使用env或者studio配置完工程后，会自动下载uffs软件包



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 12, 2021 09:49 AM
To: ***@***.***&gt;;
Cc: "Meco Jianting ***@***.******@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] [components][dfs] remove jffs2 and uffs (#4449)




 
Noted, Thanks.
 Our NK-980IOT board need the UFFS package on SPI NAND flash.
 https://github.com/RT-Thread/rt-thread/tree/master/bsp/nuvoton/nk-980iot

**Comment by yangjie11** [comment]
源码中有几个地方使用了这两个文件系统的初始化和相关宏，移入软件包使用的是PKG_USING, 原来是RT_USING, 我这边需要考虑再改一下Kconfig

**Comment by yangjie11** [comment]
uffs、jffs2作为软件包，更新 Env 索引查看：

```
-> RT-Thread online packages
    -> system packages
         [ ] JFFS2
         [ ] UFFS
```
软件包仓库地址：
- uffs：https://github.com/RT-Thread-packages/uffs
- jffs2：https://github.com/RT-Thread-packages/jffs2

**Comment by yangjie11** [comment]
ci错误可能是网络不好下载工具链出错了
image

**Comment by wosayttn** [comment]
> uffs、jffs2作为软件包，更新 Env 索引查看：
> 
> ```
> -> RT-Thread online packages
>     -> system packages
>          [ ] JFFS2
>          [ ] UFFS
> ```
> 
> 软件包仓库地址：
> 
> * uffs：https://github.com/RT-Thread-packages/uffs
> * jffs2：https://github.com/RT-Thread-packages/jffs2

Hi

Sorry to disturb you. 

I can't see these packages in my menuconfig.
How to get latest supported packages-list of RTT?

Need it update env utility or not?

**Comment by mysterywolf** [comment]
scons --upgrade 还是 pkgs --upgrade 我忘了是哪一个了&nbsp; 你都试一下&nbsp; 注意是两个-



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 6, 2021 14:39 PM
To: ***@***.***&gt;;
Cc: "Meco Jianting ***@***.******@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] [components][dfs] remove jffs2 and uffs (#4449)




  
uffs、jffs2作为软件包，更新 Env 索引查看：
 -&gt; RT-Thread online packages     -&gt; system packages          [ ] JFFS2          [ ] UFFS  
软件包仓库地址：
  
uffs：https://github.com/RT-Thread-packages/uffs 

jffs2：https://github.com/RT-Thread-packages/jffs2 
  
Hi
 
Sorry to disturb you.
 
I can't see these packages in my menuconfig.
 How to get latest supported packages-list of RTT?
 
Need it update env utility or not?

**Comment by mysterywolf** [comment]
参见这个&nbsp;
https://docs.rt-thread.org/#/development-tools/env/env?id=%e8%bd%af%e4%bb%b6%e5%8c%85%e7%ae%a1%e7%90%86%ef%bc%9apackage


---Original---
From: ***@***.***&gt;
Date: Tue, Apr 6, 2021 14:39 PM
To: ***@***.***&gt;;
Cc: "Meco Jianting ***@***.******@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] [components][dfs] remove jffs2 and uffs (#4449)




  
uffs、jffs2作为软件包，更新 Env 索引查看：
 -&gt; RT-Thread online packages     -&gt; system packages          [ ] JFFS2          [ ] UFFS  
软件包仓库地址：
  
uffs：https://github.com/RT-Thread-packages/uffs 

jffs2：https://github.com/RT-Thread-packages/jffs2 
  
Hi
 
Sorry to disturb you.
 
I can't see these packages in my menuconfig.
 How to get latest supported packages-list of RTT?
 
Need it update env utility or not?

**Comment by wosayttn** [comment]
Thanks Wolf,
I see a conflicting message shown after I executing 'pkgs --upgrade'.
After resolving it, I can see these new packages in menu.

**Pull request merged**
