### PR TITLE
release mutex when thread delete

### PR DESCRIPTION
**Pull request by skychen123**
## 拉取/合并请求描述：(PR description)

[

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

### CODE REVIEW

**Comment by BernardXiong** [comment]
请提供测试用例出来

**Comment by skychen123** [comment]
> 请提供测试用例出来

#include <stdio.h>
#include <rtthread.h>

static struct rt_mutex test_lock;

int main(void)
{
    rt_mutex_init(&test_lock, "test_heap", 1);
    rt_mutex_take(&test_lock, -1);
    printf("hello rt-thread\n");
    rt_thread_delete(rt_thread_self ());
    rt_schedule ();
    return 0;
}

**Comment by Guozhanxin** [comment]
多谢，我们最近会测试一下

**Comment by kurisaW** [comment]
经测试，在一个线程中持有互斥量，同时再将该线程删除，但是在内核处该互斥量并未得到释放

image

**Comment by kurisaW** [comment]
请在rt_thread_delete()处有关mutex的地方也加入该函数的调用

image

**Comment by Guozhanxin** [comment]
@skychen123 hello，你看我们最近测试的结果，要不要改一下

**Review by Guozhanxin — APPROVED** [review]

**Comment by Guozhanxin** [comment]
先合并此PR，然后在下个PR补齐。

**Pull request merged**
