### PR TITLE
User manual for a AT32UC3B0256 target from MCUZone

### PR DESCRIPTION
**Pull request by ramangopalan**
Dear RT-Thread Community,

[

#### 为什么提交这份PR (why to submit this PR)

I recently found the the pdf document for the AVR32 (MCUZone) dev board around at32uc3b0256. I had much difficulty in finding it. A friend (Alan) from another community helped me with a reference. This is useful for all AVR32UC3B users.

#### 你的解决方案是什么 (what is your solution)

Save reference pdf into bsp/documents

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP: /bsp/avr32/at32uc3b0256

- .config: Not applicable.

- action: Not applicable.

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

### CODE REVIEW

**Comment by mysterywolf** [comment]
Hi, thanks for your PR and please ignore the CI warning. 

Could you use a URL to instead of the pdf file, otherwise, the repo will expand a lot if everyone upload a pdf. Only reasonable pdf will be accepted.

**Comment by ramangopalan** [comment]
Dear @mysterywolf, Greetings!

> Could you use a URL to instead of the pdf file, otherwise, the repo
> will expand a lot if everyone upload a pdf. Only reasonable pdf will
> be accepted.

Many thanks for your suggestion. I fully understand and accept your
rationale. I fully understand the guidelines and how it is very
important to save code space.

In the context of MCUZone's AVR32 target board, I literally found the
schematic after years. It wasn't very easy to get the schematic.

Until recently, I used my multimeter to trace port pins :) Second: A
lot of the links on MCUZone's website are broken.

My humble request: Can you please make an exception for this case
alone? I just want for it to be a reference document for AVR32UC3B.

**Comment by supperthomas** [comment]
we think you can add the pdf in your own github repo and add repo link in readme.
You can add other file like schematic etc file by your self which we think it is very helpful.

**Comment by ramangopalan** [comment]
Dear @supperthomas,

> we think you can add the pdf in your own github repo and add repo
> link in readme.  You can add other file like schematic etc file by
> your self which we think it is very helpful.

Many thanks for your message. I understand. I will add a reference to
the pdf documents soon. For now, I have rebased to retain just the
markdown commit. Many thanks.

**Comment by supperthomas** [comment]
BTW，here are example. 

https://github.com/supperthomas/BSP_BOARD_NORDIC


You can find this link in nrf5x/nrf52840/readme.md

**Comment by ramangopalan** [comment]
Dear @supperthomas,

> https://github.com/supperthomas/BSP_BOARD_NORDIC

Thank you for the link. I will keep this in mind. Thanks again. Good
day!

**Pull request merged**
