### PR TITLE
Stable v2.0.x kinetis

### PR DESCRIPTION
**Pull request by hakehuang**
integrate the Freescale SDK1.3 to rt-thread 2.0 code base. All peripheral drivers can be used directly. for examples project please check the build directory
enable all frdm board with 5 toolchian support(iar/keil/kds/atl/armgcc(cmake))
finsh is port also.

### CODE REVIEW

**Comment by BernardXiong** [comment]
Thank you for your contribution. 

1. The stable branch does not accept any new feature. Please add the new BSP porting in to the master;
2. Please make sure the avaible boards;
3. Please use scons for building;
4. I can not known where is the RT-Thread releated porting code. 
5. ...

**Comment by hakehuang** [comment]
Is this possible to have a FSL kinetis branch for rt-thread?
1. I do not agree to use scons. There is much better support with IAR/KEIL/CMAKE/KDS.
2. the boards are list in the commit, all freescale FRDM boards are supported.
3. the porting code is located in bsp/freescale/driver_wrapper/ , Only uart related drivers are ported to enable the usage of rtthread.
4. the project file are in the build folder, you can try to open it with IAR/KEIL/KDS/ATL or you can use armgcc directly.

This branch may be variation of rt-thread, because the drivers are directly reuse from SOC vender's SDK, users will not need to write the driver for each soc any more, the rt-thread acts mainly as an task manager.

Can I have your comments on above proposal? Thanks in advance.

**Comment by BernardXiong** [comment]
So, you just use RT-Thread as a task scheduler. 

The driver of RT-Thread is made for RT-Thread components, such as finsh shell, file system, lwIP stack etc.

If you just use RT-Thread as a task scheduler, a standalone git repo is a better idea. Can you contact me directly?

**Comment by hakehuang** [comment]
How to contact your directly?

**Comment by BernardXiong** [comment]
@hakehuang You can use GITTER as the URL link in the README.md of this git repo:

https://gitter.im/RT-Thread/rt-thread

Or QQ group.

**Pull request closed without merging**
