### PR TITLE
[components][sensor]增加电源检测类型 

### PR DESCRIPTION
**Pull request by CYFS3**
## 拉取/合并请求描述：(PR description)

[

#### 为什么提交这份PR (why to submit this PR)

https://github.com/RT-Thread/rt-thread/issues/9399 和 [static int sensor(int argc, char **argv)](https://github.com/RT-Thread/rt-thread/blob/master/components/drivers/sensor/v1/sensor_cmd.c)当参数小于2是return 空
https://github.com/CYFS3/packages/commit/815fe8dce0c7b9ba4be6bd9b42c3c641e8ac5058
https://github.com/CYFS3/ina226/commit/bd94132054303f816ba3a5ccabcc63a3d64ed70
#### 你的解决方案是什么 (what is your solution)

* Sensor types增加`RT_SENSOR_CLASS_VOLTAGE` `RT_SENSOR_CLASS_CURRENT` `RT_SENSOR_CLASS_POWER`
* Sensor unit types增加 `RT_SENSOR_UNIT_MV` `RT_SENSOR_UNIT_MA` `RT_SENSOR_UNIT_MW`
* rt_sensor_data增加`float mv,ma,mw`
* 当static int sensor(int argc, char **argv)参数小于2时候返回-RT_EINVAL

#### 请提供验证的bsp和config (provide the config and bsp) 

- BSP:

- .config:

- action:

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

### CODE REVIEW

**Comment by kurisaW** [comment]
sensor_cmd.c中的sensor_show_data()函数中的power是不是没实现

**Comment by CYFS3** [comment]
> sensor_cmd.c中的sensor_show_data()函数中的power是不是没实现

已添加

**Comment by CYFS3** [comment]
https://github.com/RT-Thread/packages/pull/1780
https://github.com/xupenghu/ina226/pull/1

**Comment by CYFS3** [comment]
编译日志
~~~
scons -j32
scons: Reading SConscript files ...
Newlib version: 4.1.0
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
CC build\applications\main.o
CC build\board\board.o
CC build\board\CubeMX_Config\Src\stm32f4xx_hal_msp.o
CC build\kernel\components\drivers\core\device.o
CC build\kernel\components\drivers\i2c\dev_i2c_bit_ops.o
CC build\kernel\components\drivers\i2c\dev_i2c_core.o
CC build\kernel\components\drivers\i2c\dev_i2c_dev.o
CC build\kernel\components\drivers\ipc\completion_comm.o
CC build\kernel\components\drivers\ipc\completion_up.o
CC build\kernel\components\drivers\ipc\condvar.o
CC build\kernel\components\drivers\ipc\dataqueue.o
CC build\kernel\components\drivers\ipc\pipe.o
CC build\kernel\components\drivers\ipc\ringblk_buf.o
CC build\kernel\components\drivers\ipc\ringbuffer.o
CC build\kernel\components\drivers\ipc\waitqueue.o
CC build\kernel\components\drivers\ipc\workqueue.o
CC build\kernel\components\drivers\misc\rt_drv_pwm.o
CC build\kernel\components\drivers\pin\dev_pin.o
CC build\kernel\components\drivers\sensor\v1\sensor.o
CC build\kernel\components\drivers\sensor\v1\sensor_cmd.o
CC build\kernel\components\drivers\serial\serial.o
CC build\kernel\components\finsh\cmd.o
CC build\kernel\components\finsh\msh.o
CC build\kernel\components\finsh\msh_parse.o
CC build\kernel\components\finsh\shell.o
CC build\kernel\components\libc\compilers\common\cctype.o
CC build\kernel\components\libc\compilers\common\cstdlib.o
CC build\kernel\components\libc\compilers\common\cstring.o
CC build\kernel\components\libc\compilers\common\ctime.o
CC build\kernel\components\libc\compilers\common\cunistd.o
CC build\kernel\components\libc\compilers\common\cwchar.o
CC build\kernel\components\libc\compilers\newlib\syscalls.o
CC build\kernel\libcpu\arm\common\atomic_arm.o
CC build\kernel\libcpu\arm\common\div0.o
CC build\kernel\libcpu\arm\common\showmem.o
AS build\kernel\libcpu\arm\cortex-m4\context_gcc.o
CC build\kernel\libcpu\arm\cortex-m4\cpuport.o
CC build\kernel\src\clock.o
CC build\kernel\src\components.o
CC build\kernel\src\cpu_up.o
CC build\kernel\src\idle.o
CC build\kernel\src\ipc.o
CC build\kernel\src\irq.o
CC build\kernel\src\klibc\kstdio.o
CC build\kernel\src\klibc\kstring.o
CC build\kernel\src\kservice.o
CC build\kernel\src\mem.o
CC build\kernel\src\mempool.o
CC build\kernel\src\object.o
CC build\kernel\src\scheduler_comm.o
CC build\kernel\src\scheduler_up.o
CC build\kernel\src\thread.o
CC build\kernel\src\timer.o
CC build\libraries\HAL_Drivers\drv_common.o
CC build\libraries\STM32F4xx_HAL\CMSIS\Device\ST\STM32F4xx\Source\Templates\system_stm32f4xx.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_cec.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_cortex.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_crc.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_cryp.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_cryp_ex.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_dma.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_dma_ex.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_gpio.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_i2c.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_i2c_ex.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_lptim.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_pwr.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_pwr_ex.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_rcc.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_rcc_ex.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_rng.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_tim.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_tim_ex.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_uart.o
CC build\libraries\STM32F4xx_HAL\STM32F4xx_HAL_Driver\Src\stm32f4xx_hal_usart.o
CC build\packages\ina226-latest\example_ina226.o
CC build\packages\ina226-latest\ina226.o
CC build\packages\ina226-latest\sensor_ti_ina226.o
CC libraries\HAL_Drivers\drivers\drv_gpio.o
CC libraries\HAL_Drivers\drivers\drv_usart.o
AS libraries\STM32F4xx_HAL\CMSIS\Device\ST\STM32F4xx\Source\Templates\gcc\startup_stm32f407xx.o
LINK rt-thread.elf
Memory region         Used Size  Region Size  %age Used
            CODE:      120300 B         1 MB     11.47%
            RAM1:        5876 B       128 KB      4.48%
            RAM2:          0 GB        64 KB      0.00%
MCUlcdgrambysram:          0 GB         1 MB      0.00%
arm-none-eabi-objcopy -O ihex rt-thread.elf rtthread.hex
arm-none-eabi-size rt-thread.elf
   text    data     bss     dec     hex filename
 120300    2352    3524  126176   1ece0 rt-thread.elf
arm-none-eabi-objcopy -O binary rt-thread.elf rtthread.bin
arm-none-eabi-size rt-thread.elf
   text    data     bss     dec     hex filename
 120300    2352    3524  126176   1ece0 rt-thread.elf
scons: done building targets.
~~~

**Review by mysterywolf — APPROVED** [review]

**Pull request merged**
