### PR TITLE
完善CH32V307的串口BSP

### PR DESCRIPTION
**Pull request by muaxiaohei**
## 拉取/合并请求描述：(PR description)

[
问题：CH32V307的串口1外设挂接在APB2桥上，其余串口均挂接在APB1桥上，为保证程序正常运行做出修改。

修改：主要对`struct ch32_uart_hw_config`结构体做了一定修改与适配，修改后的结构体成员名符合要求，调用相应串口，程序运行正常。
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [x] 本拉取/合并使用[[formatting](https://github.com/mysterywolf/formatting)](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[[RT-Thread代码规范](typora://app/documentation/contribution_guide/coding_style_cn.md)](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [[RT-Thread code specification](typora://app/documentation/contribution_guide/coding_style_en.txt)](../documentation/contribution_guide/coding_style_en.txt)

### CODE REVIEW

**Comment by liYony** [comment]
drv_usart.c   62 行：
改了结构体，这里的初始化也应该更改。

**Comment by liYony** [comment]
image

**Comment by liYony** [comment]
image

**Comment by mysterywolf** [comment]
@liYony 已Approve通过

**Pull request merged**
