### PR TITLE
[Update] Sync from v4.0.3 and update change log.

### PR DESCRIPTION
**Pull request by KyleChenjh**
## 拉取/合并请求描述：(PR description)

[
同步v4.0.3版本的代码到 lts3.1.x版本，并更新相关change_log说明。
已经使用 testcase 测试通过，并且该版本已经增加了ci 测试环境.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

### CODE REVIEW

**Comment by KyleChenjh** [comment]
@Guozhanxin  已经提交，麻烦review一下，谢谢。

**Comment by Guozhanxin** [comment]
@supperthomas 我在wiki里看到nrf5x系列的bsp好像是你在维护，可以帮忙验证下这个bsp吗？https://github.com/KyleChenjh/rt-thread/tree/lts-v3.1.x/bsp/nrf51822

**Comment by Guozhanxin** [comment]
@wosayttn Hello, I found in the wiki that you are maintaining the BSP of Nuvoton series, could you please help to verify whether the related BSP in this PR works normally?

**Comment by wosayttn** [comment]
> @wosayttn Hello, I found in the wiki that you are maintaining the BSP of Nuvoton series, could you please help to verify whether the related BSP in this PR works normally?

Thanks for your notification. I checked out KyleChenjh repo., but I can't find out any nuvoton BSP sources in this repos.. 
What's the LTS version? The LTS seems like previous version?

**Comment by wosayttn** [comment]
Thanks updating. 
I tested nuvoton BSP building using produced project files, but I got all failure.
The cause is these building depends on 3rd-party packages, but no any 3rd-party packages sources in <path_to_board>/packages folder.

**Comment by KyleChenjh** [comment]
Thank you for your prompt reply.
About this compilation failure problem, You try to use  `pkgs --update` to pull 3rd-party packages from the remote server and then compile it. As shown in the figure.

image

Then use `scons --target=mdk5` to generate the project. And I have compiled successfully through this operation.

image

**Comment by wosayttn** [comment]
Thanks. I know the RTT working flow, but I think these 3rd party packages sources and file paths are not included in generated MDK project files in the LTS repository. User still need to invoke pkgs-update and re-generate to get workable MDK project file. How about remove generated MDK project files in LTS by default, same with mainstream?

**Comment by KyleChenjh** [comment]
OK, relevant questions have been updated.

**Comment by wosayttn** [comment]
Thanks.

**Comment by supperthomas** [comment]
> @supperthomas 我在wiki里看到nrf5x系列的bsp好像是你在维护，可以帮忙验证下这个bsp吗？https://github.com/KyleChenjh/rt-thread/tree/lts-v3.1.x/bsp/nrf51822

目前我们维护的都是nrf52系列nrf51暂时没有开发板可以请@luhuadong 帮忙看下，他有nrf51822开发板

**Comment by BernardXiong** [comment]
代码改动太多了，请遵循：
* 新的特性不要向lts版本合并，包括新的BSP；
* 主要是一些bugfix，内核/驱动框架/组件，这些是重点；
  * lts版本没有SMP特性，记得不要合并SMP相关的代码；
* 一些大的bsp改动也都不向lts版本合并；<例如BSP整体框架调整的>

**Pull request closed without merging**
