### PR TITLE
[bsp][stm32] fix stm431xx GetBank

### PR DESCRIPTION
**Pull request by klivelinux**
## 拉取/合并请求描述：(PR description)

[
  STM32L431xx only have single bank Flash
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

### CODE REVIEW

**Comment by klivelinux** [comment]
This is define in file  "stm32l4xx_hal_flash.h"

`/** @defgroup FLASH_Banks FLASH Banks
  * @{
  */
#define FLASH_BANK_1              ((uint32_t)0x01)                          /*!< Bank 1   */
#if defined (STM32L471xx) || defined (STM32L475xx) || defined (STM32L476xx) || defined (STM32L485xx) || defined (STM32L486xx) || \
    defined (STM32L496xx) || defined (STM32L4A6xx) || \
    defined (STM32L4R5xx) || defined (STM32L4R7xx) || defined (STM32L4R9xx) || defined (STM32L4S5xx) || defined (STM32L4S7xx) || defined (STM32L4S9xx)
#define FLASH_BANK_2              ((uint32_t)0x02)                          /*!< Bank 2   */
#define FLASH_BANK_BOTH           ((uint32_t)(FLASH_BANK_1 | FLASH_BANK_2)) /*!< Bank1 and Bank2  */
#else
#define FLASH_BANK_BOTH           ((uint32_t)(FLASH_BANK_1))                /*!< Bank 1   */
#endif`

**Comment by BernardXiong** [comment]
@sunshine0824 我看到针对l4的GetBank函数修改是你这边增加的，而下面则是通过获得一些寄存器值的方式自动判断。请确认下，在这边确实是需要对一些特殊的L4型号需要额外这样考虑吗？

@SummerGGift 也帮忙检查下。

**Comment by sunshine0824** [comment]
程序中通过    if (READ_BIT(SYSCFG->MEMRMP, SYSCFG_MEMRMP_FB_MODE) == 0)这句话判断bank号，L43x系列的参考手册中，SYSFG寄存器没有 FB_MODE位，所以加入了宏定义选择。参考手册链接https://www.st.com/content/ccc/resource/technical/document/reference_manual/group0/b0/ac/3e/8f/6d/21/47/af/DM00151940/files/DM00151940.pdf/jcr:content/translations/en.DM00151940.pdf

**Comment by hichard** [comment]
这个问题，应该问st吧？------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>
发送时间: 2019年6月9日(星期天) 中午11:43
收件人: "RT-Thread/rt-thread"<rt-thread@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [RT-Thread/rt-thread] [bsp][stm32] fix stm431xx GetBank (#2720)



程序中通过    if (READ_BIT(SYSCFG->MEMRMP, SYSCFG_MEMRMP_FB_MODE) == 0)这句话判断bank号，L43x系列的参考手册中，SYSFG寄存器没有 FB_MODE位，所以加入了宏定义选择。参考手册链接https://www.st.com/content/ccc/resource/technical/document/reference_manual/group0/b0/ac/3e/8f/6d/21/47/af/DM00151940/files/DM00151940.pdf/jcr:content/translations/en.DM00151940.pdf
 
&mdash;

**Comment by BernardXiong** [comment]
如果是这样，那么这个问题在整个L4系列中都应该存在吧？那这个宏范围应该更大些？

现在是一颗颗芯片加，这个太麻烦了：

```c
#if defined (STM32L432xx) || (STM32L431xx)
```

**Comment by sunshine0824** [comment]
目前来看是L4系列一部分芯片是该缺少寄存器标志位的，手册的最开始说明了范围STM32L41xxx/42xxx/43xxx/44xxx/45xxx/46xxx。可以考虑是否再继续通过该寄存器进行判断？
另外，stm32l4xx_hal_flash.h文件中有如下宏定义
#define FLASH_BANK_1              ((uint32_t)0x01)                          /*!< Bank 1   */
#if defined (STM32L471xx) || defined (STM32L475xx) || defined (STM32L476xx) || defined (STM32L485xx) || defined (STM32L486xx) || \
    defined (STM32L496xx) || defined (STM32L4A6xx) || \
    defined (STM32L4R5xx) || defined (STM32L4R7xx) || defined (STM32L4R9xx) || defined (STM32L4S5xx) || defined (STM32L4S7xx) || defined (STM32L4S9xx)
#define FLASH_BANK_2              ((uint32_t)0x02)                          /*!< Bank 2   */
#define FLASH_BANK_BOTH           ((uint32_t)(FLASH_BANK_1 | FLASH_BANK_2)) /*!< Bank1 and Bank2  */
#else
#define FLASH_BANK_BOTH           ((uint32_t)(FLASH_BANK_1))                /*!< Bank 1   */
#endif
是否可以考虑通过FLASH_BANK_BOTH 的值进行判断？

**Comment by BernardXiong** [comment]
如果都有，建议能够按照芯片系列来进行宏条件判断

**Pull request closed without merging**
