### PR TITLE
[components] dfs: update elmfat to R0.14 patch 1

### PR DESCRIPTION
**Pull request by cliff-cmc**
merge from https://github.com/abbrev/fatfs.git
(cf1fa008119c8ae2d05311ba3d97da0c4dca33b6)

Signed-off-by: Cliff Chen <cliff.chen@rock-chips.com>
Change-Id: I321ba7933e1a4d6c07b3fbaa2a134eb54bb43b32

## 拉取/合并请求描述：(PR description)

[
有些产品要支持多国语言，所以会有unicode的需求，目前的fat只支持utf16，对os和编译器的兼容性都不太好，所以从这个fat的原始开源项目上合并了最新的代码，可以支持utf8，同时可以解决一下exfat的bug，详见版本的发布记录。

合并的时候，只修改api兼容性问题，保留了绝大部分移植代码和所有的fat开源项目原始代码。
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other style
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality

### CODE REVIEW

**Comment by BernardXiong** [comment]
@Guozhanxin Please make a test for different platform and multi-partition.

**Comment by mysterywolf** [comment]
@Guozhanxin  测试时请留意 新版的FATFS格式化函数和老版的FATFS格式化函数参数不太一样

**Review by balanceTWK — APPROVED** [review]
image


在 stm32f407-atk-explorer 上跑测试用例正常。

**Review by balanceTWK — APPROVED** [review]
image

**Comment by BernardXiong** [comment]
Please make more test on multi-volumes cases, include mount, mkfs, umount, and file/directory etc. @balanceTWK

**Pull request merged**
