### PR TITLE
add bsp stm32l072

### PR DESCRIPTION
**Pull request by AubrCool**
add bsp stm32l072
not add scons configures

### CODE REVIEW

**Comment by BernardXiong** [comment]
Please add scons script, thanks.

**Comment by AubrCool** [comment]
OK ! Added  scons script.

**Comment by BernardXiong** [comment]
Is it ready?

2016-09-22 12:38 GMT+08:00 Aubr.Cool <notifications@github.com>:

**Comment by AubrCool** [comment]
???

**Pull request merged**
