### PR TITLE
Mdio总线需要锁 挂上两个从机之后会抢总线

### PR DESCRIPTION
**Pull request by Yohozzy**
## 拉取/合并请求描述：(PR description)
Mdio总线需要锁 挂上两个从机之后会抢总线
[

#### 在什么测试环境下测试通过 (what is the test environment)

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [ ] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

### CODE REVIEW

**Comment by mysterywolf** [comment]
这个只是声明了一个互斥量 并没有实际使用到啊

**Comment by Yohozzy** [comment]
这需要去改drv_mdio.c 里面的mdio总线操作

毕竟是总线 我遇到的问题是我两个phy正好挂在同一条mdio总线上 同时使用的时候争抢了总线控制权导致通信错乱

static rt_size_t rt_hw_mdio_read(void *bus, rt_uint32_t addr, rt_uint32_t reg, void *data, rt_uint32_t size)
{
    struct rt_mdio_bus *bus_obj = (struct rt_mdio_bus *)bus;

    rt_uint32_t counter;
    RT_ASSERT(data);
    rt_uint32_t *data_ptr = (rt_uint32_t *)data;

    if (4 != size)
    {
        return 0;
    }
    
    rt_mutex_take(bus_obj->lock, RT_WAITING_FOREVER);

    /* Clear the MII interrupt event. */
    ENET_ClearInterruptStatus((ENET_Type *)(bus_obj->hw_obj), ENET_EIR_MII_MASK);

    /* Starts a SMI read command operation. */
    ENET_StartSMIRead((ENET_Type *)(bus_obj->hw_obj), addr, reg, kENET_MiiReadValidFrame);

    /* Wait for MII complete. */
    for (counter = PHY_TIMEOUT_COUNT; counter > 0; counter--)
    {
        if (ENET_GetInterruptStatus((ENET_Type *)(bus_obj->hw_obj)) & ENET_EIR_MII_MASK)
        {
            break;
        }
    }

    /* Check for timeout. */
    if (!counter)
    {
        // return kStatus_PHY_SMIVisitTimeout;
        rt_mutex_release(bus_obj->lock);
        return 0;
    }

    /* Get data from MII register. */
    *data_ptr = ENET_ReadSMIData((ENET_Type *)(bus_obj->hw_obj));

    /* Clear MII interrupt event. */
    ENET_ClearInterruptStatus((ENET_Type *)bus_obj->hw_obj, ENET_EIR_MII_MASK);

    rt_mutex_release(bus_obj->lock);
    return 4;
}

**Comment by Yohozzy** [comment]
这个drv_mdio文件应该有专人维护
[https://github.com/RT-Thread/rt-thread/blob/master/bsp/imxrt/libraries/drivers/drv_mdio.c](url)
需要我也提交吗?

**Comment by Guozhanxin** [comment]
> 这个drv_mdio文件应该有专人维护
> 
> https://github.com/RT-Thread/rt-thread/blob/master/bsp/imxrt/libraries/drivers/drv_mdio.c
> 
> 需要我也提交吗?

需要的，提交上来之后可以找他们帮忙review

**Comment by Yohozzy** [comment]
那我关掉 我给维护的人提下建议就行

**Pull request closed without merging**
