### PR TITLE
增加双网口配置选项，增加phy8211F 驱动

### PR DESCRIPTION
**Pull request by xjy198903**
## 拉取/合并请求描述：(PR description)

[
这段方括号里的内容是您**必须填写并替换掉**的，否则PR不可能被合并。**方括号外面的内容不需要修改，但请仔细阅读。**
The content in this square bracket must be filled in and replaced, otherwise, PR can not be merged. The contents outside square brackets need not be changed, but please read them carefully.

请在这里填写您的PR描述，可以包括以下之一的内容：为什么提交这份PR；解决的问题是什么，你的解决方案是什么；
Please fill in your PR description here, which can include one of the following items: why to submit this PR; what is the problem solved and what is your solution;

并确认并列出已经在什么情况或板卡上进行了测试。
And confirm in which case or board has been tested.
]

以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in the submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use a web browser to visit PR, and check items one by one, and ticked them if no problem.

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [ ] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [ ] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [ ] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [ ] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [ ] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 本拉取/合并请求代码是高质量的 Code in this PR is of high quality
- [ ] 本拉取/合并使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](../documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](../documentation/contribution_guide/coding_style_en.txt)

### CODE REVIEW

**Comment by xjy198903** [comment]
drv_eth.c需要适配下，目前新加载的BSP网络驱动可能已不适合drv_eth.c的使用

**Review by mysterywolf — APPROVED** [review]

**Comment by mysterywolf** [comment]
我先合并这个 如果你有时间可以再提交一个PR上来

**Comment by mysterywolf** [comment]
已合并，感谢贡献PR！

**Comment by xjy198903** [comment]
我现在还没在新的1170BSP下调通rtl8211f，系统加载后，网卡能正常识别，但发起ping指令一直超时，我怀疑是drv_eth.c的问题，但暂时还没找到突破口

**Comment by mysterywolf** [comment]
ping我一下邮箱 拉你进社区群 meco@rt-thread.org

**Comment by xjy198903** [comment]
用开发主机ping 吗

**Comment by mysterywolf** [comment]
不是 就往我邮箱里随便发些什么东西，我回你个微信群二维码😂 不是网络的ping

**Comment by xjy198903** [comment]
已发邮件到jiantingman@foxmail.com

**Pull request merged**
