### PR TITLE
AT32UC3B: Fix compilation problem for BSP by defining RT_CPUS_NR

### PR DESCRIPTION
**Pull request by ramangopalan**
[

为什么提交这份PR (why to submit this PR)

Fix compilation problem for the AT32UC3B0 BSP. Here is the gist of the
error:

AS build\kernel\libcpu\avr32\uc3\context_gcc.o
CC build\kernel\src\idle.o
C:\Skullets\rt-thread\rt-thread\src\idle.c:46: error: 'RT_CPUS_NR' undeclared here (not in a function)
scons: *** [build\kernel\src\idle.o] Error 1
scons: building terminated because of errors.

你的解决方案是什么 (what is your solution)

I confirm that the recent change to src/idle.c removes the check for
RT_USING_SMP. Fix compilation problem by defining the symbol
RT_CPUS_NR as 1.

在什么测试环境下测试通过 (what is the test environment)

AVR32UC3B0256 development kit (MCUZone) - The AVR32DEV1.

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [x] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [ ] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [ ] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

### CODE REVIEW

**Comment by geniusgogo** [comment]
重新menuconfig就会定义出RT_CPUS_NR

**Comment by supperthomas** [comment]
Please update menuconfig as PR #8151

**Comment by ramangopalan** [comment]
Dear @supperthomas, many thanks for your message. I am sorry. I don't understand this part. I checked @geniusgogo's PR. While I see the changes to the rt core header files, I don't see a reference to Kconfig. OR do you mean the BSP's Kconfig should define the RT_CPUS_NR symbol? Can you please elaborate?

**Comment by supperthomas** [comment]
https://github.com/RT-Thread/rt-thread/blob/43f96b3f8598aaa2a808a5a5b72482d662dfcc20/src/Kconfig#L68-L72


you can get this config from newest code. Just use `menuconfig` to update the .config.

**Comment by ramangopalan** [comment]
Dear @supperthomas, thank you for your suggestion. I understand. I have updated the .config now.

**Review by supperthomas — APPROVED** [review]

**Pull request merged**
