### PR TITLE
[Bsp] stm32f10x usart correct rx parity err

### PR DESCRIPTION
**Pull request by AubrCool**

### CODE REVIEW

**Comment by BernardXiong** [comment]
It seems building failed in this bsp.

2017-04-13 12:51 GMT+08:00 Aubr.Cool <notifications@github.com>:

**Comment by AubrCool** [comment]
stmf32f10x build succeed

**Comment by BernardXiong** [comment]
You can check ci building information:
https://travis-ci.org/RT-Thread/rt-thread

**Comment by BernardXiong** [comment]
Oh, it may caused by time API.

**Pull request merged**
