### PR TITLE
[nuvoton] Sync upstream

### PR DESCRIPTION
**Pull request by wosayttn**
## 拉取/合并请求描述：(PR description)

[
1. Sync upstream after rt-smart merging.
2. Add NuMaker-IoT-MA35D1 BSP.
]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting)等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

### CODE REVIEW

**Review by mysterywolf — APPROVED** [review]

**Comment by BernardXiong** [comment]
手快，这里有个bin文件呢：`bsp/nuvoton/ma35-rtp/rtthread.bin`

**Comment by wosayttn** [comment]
> 
Hi,

這個 binary 是 MA35D1 內的 CM4 核心執行的 rt-thread.bin。在編譯 NuMaker-IoT-MA35D1 與 NuMaker-HMI-MA35D1 時，會把它 INCBIN(../ma35-rtp/rtthread.bin)進來，A35 啟動時會加載它給CM4執行。謝謝。

因為 scons 沒有連帶編繹另一個 BSP 的方式，所以留下它。

**Comment by solarfern1** [comment]
Hi, 

Sorry it might be a noob question, i was wondering if anyone could help with the n9h30 BSP.
When i import other board folders in the rt-thread-master package seem to work correctly, the n9h30 seems to throw errors 

It appears to be looking for rtconfig.h, i have both rtconfig.pyc and rtconfig.py in that folder 
perhaps i need to generate the .h file , or try and create a bsp from scratch ?

Any help would be greatly appreciated 
cheers 

##############
i'm using  RT-Thread Studio Version: 2.2.6

from log file:
E:\rt-thread-master\bsp\nuvoton\nk-n9h30\board>scons --dist-ide --project-path=C:\RT-ThreadStudio\workspace/23123 --project-name=23123 
File "c:\rt-threadstudio\platform\env_released\env\tools\python27\lib\site-packages\scons\SCons\Script\Main.py", line 940, in _main
E:\rt-thread-master\bsp\nuvoton\nk-n9h30>scons --dist-ide --project-path=C:\RT-ThreadStudio\workspace/23123 --project-name=23123 
IOError: [Errno 2] No such file or directory: 'rtconfig.h':
  File "E:\rt-thread-master\bsp\nuvoton\nk-n9h30\SConstruct", line 43:
    objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)
  File "E:\rt-thread-master\tools\building.py", line 282:
    f = open('rtconfig.h', 'r')
  File "c:\rt-threadstudio\platform\env_released\env\tools\python27\lib\site-packages\scons\SCons\Platform\win32.py", line 99:
    *args, **kwargs)

**Comment by wosayttn** [comment]
Hi,

The log shown the rtconfig.h missing. Please generate rtconfig.h before exporting RTT studio project.
And, execute below commands to download related packages and settings before building.

```
menuconfig --generate
pkgs --update
scons -j 16
```

Btw, You also import NK-N9H30 RTT studio SDK-BSP packages using RTT-Studio SDKManager.

**Comment by solarfern1** [comment]
Amazing, Thanks for the superfast response, i'll give it a try

**Pull request merged**
