### PR TITLE
AT32UC3B: Update configuration files to define RT_BACKTRACE_LEVEL_MAX_NR

### PR DESCRIPTION
**Pull request by ramangopalan**
[

Dear RT-Thread Community, I trust you're all doing so well.

为什么提交这份PR (why to submit this PR)

The compilation for the AT32UC3B target fails without the definition
of the RT_BACKTRACE_LEVEL_MAX_NR symbol.

你的解决方案是什么 (what is your solution)

I just had to rebase at my end and re-run menuconfig. The config file
defines RT_BACKTRACE_LEVEL_MAX_NR. The compilation is successful.

在什么测试环境下测试通过 (what is the test environment)

I tested the build with my AVR32DEV1 (MCUZone) development kit. I also
tested this with my Mizar32-B target board. I haven't published those
yet. I will soon. Many thanks.

]

### 当前拉取/合并请求的状态 Intent for your PR

必须选择一项 Choose one (Mandatory):

- [ ] 本拉取/合并请求是一个草稿版本 This PR is for a code-review and is intended to get feedback
- [x] 本拉取/合并请求是一个成熟版本 This PR is mature, and ready to be integrated into the repo

### 代码质量 Code Quality：

我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

- [x] 已经仔细查看过代码改动的对比 Already check the difference between PR and old code
- [x] 代码风格正确，包括缩进空格，命名及其他风格 Style guide is adhered to, including spacing, naming and other styles
- [x] 没有垃圾代码，代码尽量精简，不包含`#if 0`代码，不包含已经被注释了的代码 All redundant code is removed and cleaned up
- [x] 所有变更均有原因及合理的，并且不会影响到其他软件组件代码或BSP All modifications are justified and not affect other components or BSP
- [x] 对难懂代码均提供对应的注释 I've commented appropriately where code is tricky
- [x] 代码是高质量的 Code in this PR is of high quality
- [x] 已经使用[formatting](https://github.com/mysterywolf/formatting) 等源码格式化工具确保格式符合[RT-Thread代码规范](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_cn.md) This PR complies with [RT-Thread code specification](https://github.com/RT-Thread/rt-thread/blob/master/documentation/contribution_guide/coding_style_en.md)

### CODE REVIEW

**Review by supperthomas — APPROVED** [review]

**Comment by supperthomas** [comment]
Thanks for PR. You can add you device in https://github.com/RT-Thread/rt-thread/blob/master/.github/workflows/action.yml for CI build.

**Comment by ramangopalan** [comment]
Dear @supperthomas, Greetings!

Firstly: Thank you very much for your response. Frankly, I've been
thinking about your suggestion ever since the build failed last week
because of RT_CPUS_NR.

I really want to think in this direction and help check AVR32 builds
for possible problems. I am currently using Windows for my work with
RT-Thread. I use Atmel-ICE for programming and debug sessions with
Microchip Studio (version: 7.0.2594).

The toolchain for AVR32 (avr32-gcc) on GNU/Linux (and in my context,
debug capability) has been a problem for a while.

Second: I really think Martin Guy's work [1] will help. I am not sure
if building the toolchain within the CI's recipe is a good idea.
Assuming we can build the toolchain (which I can help test and
verify), is it possible to host the toolchain somewhere so the CI
boilerplate finds it? OR is there another way?

Can you please give me your thoughts on this? Thank you very much.

References:
[1]: https://gitlab.com/martinwguy/ct-ng-avr32

**Comment by mysterywolf** [comment]
Thanks I will merge this ahead!

**Review by mysterywolf — APPROVED** [review]

**Comment by supperthomas** [comment]
> Dear @supperthomas, Greetings!
> 
> Firstly: Thank you very much for your response. Frankly, I've been thinking about your suggestion ever since the build failed last week because of RT_CPUS_NR.
> 
> I really want to think in this direction and help check AVR32 builds for possible problems. I am currently using Windows for my work with RT-Thread. I use Atmel-ICE for programming and debug sessions with Microchip Studio (version: 7.0.2594).
> 
> The toolchain for AVR32 (avr32-gcc) on GNU/Linux (and in my context, debug capability) has been a problem for a while.
> 
> Second: I really think Martin Guy's work [1] will help. I am not sure if building the toolchain within the CI's recipe is a good idea. Assuming we can build the toolchain (which I can help test and verify), is it possible to host the toolchain somewhere so the CI boilerplate finds it? OR is there another way?
> 
> Can you please give me your thoughts on this? Thank you very much.
> 
> References: [1]: https://gitlab.com/martinwguy/ct-ng-avr32

yeah ,you're right. We need The toolchain for AVR32 (avr32-gcc) on GNU/Linux which is necessary for CI .
If you face some problem , you can share the reproduce and problem picture in issue. We can help deal with the problem together.
the toolchain can be push to https://github.com/RT-Thread/toolchains-ci just like other toolchain.
You can try codespace for testing. I think this will be helpful.
image

**Comment by ramangopalan** [comment]
Dear @supperthomas, many thanks for your response. I understand. Once
I have the base infrastructure for the Mizar32 target, I will help
construct the avr32-gcc using Martin Guy's work. I will stay in touch
with you to seek your inputs on what the best way is to get the
avr32-gcc to toolchains-ci. Thank you.

**Comment by ramangopalan** [comment]
Dear @supperthomas, Dear @mysterywolf, Greetings!

I trust you're doing so well.

I revisited Martin's crosstool-NG [1] for constructing an AVR32
toolchain for work with RT-Thread. Unfortunately, wget fails within
the invocation. The recipe fails to get the zip files from Microchip; 
specifically, the Atmel header files for AVR32.

I have manually downloaded the executables (for both x86 and x86_64 +
the headers) and hosted them here [2] as-is. Luckily, the recipe from
Martin's Mizar32 Wiki [3] works. Can you please check if this is fit
for CI? I have tested this toolchain. It works. Can you please give me
your thoughts on how to proceed?

Many thanks!

P.S. I haven't tried codespace yet. I will give it a try tomorrow.

References:
[1]: https://gitlab.com/martinwguy/ct-ng-avr32
[2]: https://github.com/ramangopalan/avr32-gnu-toolchain-linux_x86
[3]: https://en.wikibooks.org/wiki/Mizar32/Compiling_eLua

**Comment by supperthomas** [comment]
> Dear @supperthomas, Dear @mysterywolf, Greetings!
> 
> I trust you're doing so well.
> 
> I revisited Martin's crosstool-NG [1] for constructing an AVR32 toolchain for work with RT-Thread. Unfortunately, wget fails within the invocation. The recipe fails to get the zip files from Microchip; specifically, the Atmel header files for AVR32.
> 
> I have manually downloaded the executables (for both x86 and x86_64 + the headers) and hosted them here [2] as-is. Luckily, the recipe from Martin's Mizar32 Wiki [3] works. Can you please check if this is fit for CI? I have tested this toolchain. It works. Can you please give me your thoughts on how to proceed?
> 
> Many thanks!
> 
> P.S. I haven't tried codespace yet. I will give it a try tomorrow.
> 
> References: [1]: https://gitlab.com/martinwguy/ct-ng-avr32 [2]: https://github.com/ramangopalan/avr32-gnu-toolchain-linux_x86 [3]: https://en.wikibooks.org/wiki/Mizar32/Compiling_eLua

It seem ok for CI. 
Can you try codespace in this link?
If you can `scons` successfully and run very well. You can add cmd in .github/workflow/action.yml just like other bsp.

**Comment by ramangopalan** [comment]
Dear @supperthomas, Greetings!

Many thanks for your suggestion. I tried Codespaces. I simply love it!
I started a Codespaces session with RT-Thread just a while ago.

I quickly cloned the avr32-gcc toolchain from [1] and tried
compilation with bsp/avr32/at32uc3b0256. With exception to the
following error for the at32uc3b0256 target which I fixed temporarily
by including string.h for cstdlib.c:

```
root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256# scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build
CC build/application.o
CC build/board.o
CC build/drivers/drv_gpio.o
CC build/drivers/drv_uart.o
CC build/kernel/components/drivers/core/device.o
CC build/kernel/components/drivers/ipc/completion.o
CC build/kernel/components/drivers/ipc/dataqueue.o
CC build/kernel/components/drivers/ipc/pipe.o
CC build/kernel/components/drivers/ipc/ringblk_buf.o
CC build/kernel/components/drivers/ipc/ringbuffer.o
CC build/kernel/components/drivers/ipc/waitqueue.o
CC build/kernel/components/drivers/ipc/workqueue.o
CC build/kernel/components/drivers/misc/pin.o
CC build/kernel/components/drivers/serial/serial.o
CC build/kernel/components/finsh/cmd.o
CC build/kernel/components/finsh/msh.o
CC build/kernel/components/finsh/msh_parse.o
CC build/kernel/components/finsh/shell.o
CC build/kernel/components/libc/compilers/common/cctype.o
CC build/kernel/components/libc/compilers/common/cstdlib.o
/workspaces/rt-thread/components/libc/compilers/common/cstdlib.c: In function 'ltoa':
/workspaces/rt-thread/components/libc/compilers/common/cstdlib.c:83: error: 'NULL' undeclared (first use in this function)
/workspaces/rt-thread/components/libc/compilers/common/cstdlib.c:83: note: each undeclared identifier is reported only once for each function it appears in
/workspaces/rt-thread/components/libc/compilers/common/cstdlib.c: In function 'ultoa':
/workspaces/rt-thread/components/libc/compilers/common/cstdlib.c:155: error: 'NULL' undeclared (first use in this function)
scons: *** [build/kernel/components/libc/compilers/common/cstdlib.o] Error 1
scons: building terminated because of errors.
root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256# 
```

The build finishes successfully.

```
CC build/kernel/components/libc/compilers/common/cstdlib.o
CC build/kernel/components/libc/compilers/common/cstring.o
CC build/kernel/components/libc/compilers/common/ctime.o
CC build/kernel/components/libc/compilers/common/cunistd.o
CC build/kernel/components/libc/compilers/common/cwchar.o
AS build/kernel/libcpu/avr32/uc3/context_gcc.o
CC build/kernel/libcpu/avr32/uc3/cpu.o
AS build/kernel/libcpu/avr32/uc3/exception_gcc.o
CC build/kernel/libcpu/avr32/uc3/interrupt.o
CC build/kernel/libcpu/avr32/uc3/stack.o
CC build/kernel/src/clock.o
CC build/kernel/src/components.o
CC build/kernel/src/idle.o
CC build/kernel/src/ipc.o
CC build/kernel/src/irq.o
CC build/kernel/src/kservice.o
CC build/kernel/src/mem.o
CC build/kernel/src/mempool.o
CC build/kernel/src/object.o
CC build/kernel/src/scheduler_up.o
CC build/kernel/src/thread.o
CC build/kernel/src/timer.o
CC build/software_framework/drivers/adc/adc.o
CC build/software_framework/drivers/flashc/flashc.o
CC build/software_framework/drivers/gpio/gpio.o
CC build/software_framework/drivers/intc/intc.o
CC build/software_framework/drivers/pm/pm.o
CC build/software_framework/drivers/pm/pm_conf_clocks.o
CC build/software_framework/drivers/pm/power_clocks_lib.o
CC build/software_framework/drivers/usart/usart.o
CC build/startup.o
LINK rtthread-uc3b0256.elf
avr32-objcopy -O binary rtthread-uc3b0256.elf rtthread.bin
avr32-size rtthread-uc3b0256.elf
   text    data     bss     dec     hex filename
  44640    1804    8860   55304    d808 rtthread-uc3b0256.elf
scons: done building targets.
root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256#
```

Just to note my immediate thoughts (and questions):

  1) The toolchain works. Like you suggested, adding the BSP to the CI
  workflow will ensure that changes across common files in the
  codebase won't break the build for AVR32.

  2) With regards to the error (with cstdlib.c) above: Do you think
  including string.h there is correct? The build for at32uc3b0256
  however passes fine with regards to cstdlib.c on my Windows
  machine. I am surprised. I am not sure what I'm getting wrong.

  3) I also reported a compilation problem/issue with regards to
  _execve_r's signature [2] a few weeks earlier. I am surprised that
  this problems doesn't show up while executing the build on
  Codespaces.

  4) I compared the version details of the avr32-gcc instances;
  i.e. the one running on my Windows machine and the one that I cloned
  from [1] on Codespaces. They are just the same!

  ```
  root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256# avr32-gcc --version
  avr32-gcc (AVR_32_bit_GNU_Toolchain_3.4.2_435) 4.4.7
  Copyright (C) 2010 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  
  root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256#
  ```

  5) Does this happen often with other BSP targets? Do you see
  instances where a build might complain locally and pass successfully
  during CI? (and the other way around too?).

  6) This is just for my understanding: Is there any way that an
  exception can be made OR signalled by the RT-Thread code reviewers
  (before accepting a PR in general) should the build fail during CI?
  Does this happen at all?

  7) I glanced through action.yml. Thank you for the link. I
  understand how it works. Do you think it is better to fix the builds
  locally before adding the BSP to actions.yml?

Finally, about the link [3] you sent me for toolchains for RT-Thread's
CI: How can I help move [1] to [3]? Please let me know if I can
help with something.

@supperthomas, many thanks for RT-Thread. It is so much fun!

Best regards,

References:
[1]: https://github.com/ramangopalan/avr32-gnu-toolchain-linux_x86
[2]: https://github.com/RT-Thread/rt-thread/issues/8181
[3]: https://github.com/RT-Thread/toolchains-ci

**Comment by supperthomas** [comment]
> Dear @supperthomas, Greetings!
> 
> Many thanks for your suggestion. I tried Codespaces. I simply love it! I started a Codespaces session with RT-Thread just a while ago.
> 
> I quickly cloned the avr32-gcc toolchain from [1] and tried compilation with bsp/avr32/at32uc3b0256. With exception to the following error for the at32uc3b0256 target which I fixed temporarily by including string.h for cstdlib.c:
> 
> ```
> root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256# scons
> scons: Reading SConscript files ...
> scons: done reading SConscript files.
> scons: Building targets ...
> scons: building associated VariantDir targets: build
> CC build/application.o
> CC build/board.o
> CC build/drivers/drv_gpio.o
> CC build/drivers/drv_uart.o
> CC build/kernel/components/drivers/core/device.o
> CC build/kernel/components/drivers/ipc/completion.o
> CC build/kernel/components/drivers/ipc/dataqueue.o
> CC build/kernel/components/drivers/ipc/pipe.o
> CC build/kernel/components/drivers/ipc/ringblk_buf.o
> CC build/kernel/components/drivers/ipc/ringbuffer.o
> CC build/kernel/components/drivers/ipc/waitqueue.o
> CC build/kernel/components/drivers/ipc/workqueue.o
> CC build/kernel/components/drivers/misc/pin.o
> CC build/kernel/components/drivers/serial/serial.o
> CC build/kernel/components/finsh/cmd.o
> CC build/kernel/components/finsh/msh.o
> CC build/kernel/components/finsh/msh_parse.o
> CC build/kernel/components/finsh/shell.o
> CC build/kernel/components/libc/compilers/common/cctype.o
> CC build/kernel/components/libc/compilers/common/cstdlib.o
> /workspaces/rt-thread/components/libc/compilers/common/cstdlib.c: In function 'ltoa':
> /workspaces/rt-thread/components/libc/compilers/common/cstdlib.c:83: error: 'NULL' undeclared (first use in this function)
> /workspaces/rt-thread/components/libc/compilers/common/cstdlib.c:83: note: each undeclared identifier is reported only once for each function it appears in
> /workspaces/rt-thread/components/libc/compilers/common/cstdlib.c: In function 'ultoa':
> /workspaces/rt-thread/components/libc/compilers/common/cstdlib.c:155: error: 'NULL' undeclared (first use in this function)
> scons: *** [build/kernel/components/libc/compilers/common/cstdlib.o] Error 1
> scons: building terminated because of errors.
> root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256# 
> ```
> 
> The build finishes successfully.
> 
> ```
> CC build/kernel/components/libc/compilers/common/cstdlib.o
> CC build/kernel/components/libc/compilers/common/cstring.o
> CC build/kernel/components/libc/compilers/common/ctime.o
> CC build/kernel/components/libc/compilers/common/cunistd.o
> CC build/kernel/components/libc/compilers/common/cwchar.o
> AS build/kernel/libcpu/avr32/uc3/context_gcc.o
> CC build/kernel/libcpu/avr32/uc3/cpu.o
> AS build/kernel/libcpu/avr32/uc3/exception_gcc.o
> CC build/kernel/libcpu/avr32/uc3/interrupt.o
> CC build/kernel/libcpu/avr32/uc3/stack.o
> CC build/kernel/src/clock.o
> CC build/kernel/src/components.o
> CC build/kernel/src/idle.o
> CC build/kernel/src/ipc.o
> CC build/kernel/src/irq.o
> CC build/kernel/src/kservice.o
> CC build/kernel/src/mem.o
> CC build/kernel/src/mempool.o
> CC build/kernel/src/object.o
> CC build/kernel/src/scheduler_up.o
> CC build/kernel/src/thread.o
> CC build/kernel/src/timer.o
> CC build/software_framework/drivers/adc/adc.o
> CC build/software_framework/drivers/flashc/flashc.o
> CC build/software_framework/drivers/gpio/gpio.o
> CC build/software_framework/drivers/intc/intc.o
> CC build/software_framework/drivers/pm/pm.o
> CC build/software_framework/drivers/pm/pm_conf_clocks.o
> CC build/software_framework/drivers/pm/power_clocks_lib.o
> CC build/software_framework/drivers/usart/usart.o
> CC build/startup.o
> LINK rtthread-uc3b0256.elf
> avr32-objcopy -O binary rtthread-uc3b0256.elf rtthread.bin
> avr32-size rtthread-uc3b0256.elf
>    text    data     bss     dec     hex filename
>   44640    1804    8860   55304    d808 rtthread-uc3b0256.elf
> scons: done building targets.
> root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256#
> ```
> 
> Just to note my immediate thoughts (and questions):
> 
> 1. The toolchain works. Like you suggested, adding the BSP to the CI
>    workflow will ensure that changes across common files in the
>    codebase won't break the build for AVR32.
> 2. With regards to the error (with cstdlib.c) above: Do you think
>    including string.h there is correct? The build for at32uc3b0256
>    however passes fine with regards to cstdlib.c on my Windows
>    machine. I am surprised. I am not sure what I'm getting wrong.
> 3. I also reported a compilation problem/issue with regards to
>    _execve_r's signature [2] a few weeks earlier. I am surprised that
>    this problems doesn't show up while executing the build on
>    Codespaces.
> 4. I compared the version details of the avr32-gcc instances;
>    i.e. the one running on my Windows machine and the one that I cloned
>    from [1] on Codespaces. They are just the same!
> 
> ```
> root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256# avr32-gcc --version
> avr32-gcc (AVR_32_bit_GNU_Toolchain_3.4.2_435) 4.4.7
> Copyright (C) 2010 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> root@codespaces-dd84d6:/workspaces/rt-thread/bsp/avr32/at32uc3b0256#
> ```
> 
> 5. Does this happen often with other BSP targets? Do you see
>    instances where a build might complain locally and pass successfully
>    during CI? (and the other way around too?).
> 6. This is just for my understanding: Is there any way that an
>    exception can be made OR signalled by the RT-Thread code reviewers
>    (before accepting a PR in general) should the build fail during CI?
>    Does this happen at all?
> 7. I glanced through action.yml. Thank you for the link. I
>    understand how it works. Do you think it is better to fix the builds
>    locally before adding the BSP to actions.yml?
> 
> Finally, about the link [3] you sent me for toolchains for RT-Thread's CI: How can I help move [1] to [3]? Please let me know if I can help with something.
> 
> @supperthomas, many thanks for RT-Thread. It is so much fun!
> 
> Best regards,
> 
> References: [1]: https://github.com/ramangopalan/avr32-gnu-toolchain-linux_x86 [2]: #8181 [3]: https://github.com/RT-Thread/toolchains-ci

Thanks for feedback.
too many problems. I can exaplain some situation.
1. CI is in ubuntu which will contain some head file of libc. So will happen some build is fail in windows, but CI is successfully.
2. CI can't confirm full situation build, like windows, mac os, linux. But it will help confirm some build situation like ubuntu. The main task is to confirm some simple build error. At least , in ubuntu the build is ok will make sure the simple build error will not happen.At least we think it's helpful
3. How can I help move [1] to [3]? Please let me know if I can help with something.
=> you may not need move [1] to [3] , you can use the [1] link firstly. We will help move the link.

**Pull request merged**
